import re

with open('lib/features/employer/jobs/employer_job_provider.dart', 'r') as f:
    content = f.read()

jobs_data = r"""[
        Job(
          id: 1,
          title: 'Software Engineer',
          description: '[{"insert":"We are looking for a skilled Software Engineer to join our dynamic team. You will be responsible for building high-performance, scalable applications. Your daily tasks will include writing clean, maintainable code, reviewing pull requests, and collaborating with cross-functional teams.\\n"}]',
          category: 'Engineering',
          employmentType: 'Full-Time',
          workplaceType: 'Remote',
          location: 'San Francisco, USA',
          salaryMin: '\$120,000',
          salaryMax: '\$160,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
          closesAt: DateTime.now().add(const Duration(days: 28)),
          applicantCount: 5,
          viewCount: 120,
          responsibilities: '• Develop and maintain scalable software solutions\n• Collaborate with cross-functional teams\n• Write clean, robust, and well-documented code\n• Conduct code reviews and provide feedback\n• Troubleshoot, debug and optimize applications',
          requiredSkills: '• 3+ years of experience in Software Development\n• Strong proficiency in Dart and Flutter\n• Experience with RESTful APIs\n• Familiarity with Git and CI/CD pipelines',
          preferredSkills: ['Node.js', 'AWS', 'Docker', 'Agile Methodologies'],
          benefits: ['Health Insurance', 'Remote Work', 'Gym Membership', '401(k) Matching', 'Unlimited PTO'],
          education: 'Bachelor\'s Degree in Computer Science or related field',
          openings: '3',
          applyVia: 'platform',
          resumeRequirement: 'required',
          coverLetterRequirement: 'optional',
          experienceLevel: 'Mid-Level',
          languages: ['English'],
          certifications: ['AWS Certified Developer'],
          ageMin: '22',
          ageMax: '45',
          screeningQuestions: [
            {'text': 'Do you have 3+ years of experience in Flutter?', 'is_required': true},
            {'text': 'Are you comfortable working in a fully remote environment?', 'is_required': true},
          ],
        ),
        Job(
          id: 2,
          title: 'Website Developer',
          description: '[{"insert":"Looking for an experienced Website Developer to design, build, and maintain our company websites. You should be proficient in modern web frameworks and have a strong eye for UI/UX design. You will work closely with the marketing team to ensure optimal website performance and SEO.\\n"}]',
          category: 'Engineering',
          employmentType: 'Full-Time',
          workplaceType: 'Hybrid',
          location: 'New York, USA',
          salaryMin: '\$90,000',
          salaryMax: '\$130,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
          closesAt: DateTime.now().add(const Duration(days: 15)),
          applicantCount: 2,
          viewCount: 85,
          responsibilities: '• Build scalable, responsive web applications\n• Optimize websites for maximum speed and scalability\n• Implement SEO best practices\n• Work with the design team to bridge the gap between graphical design and technical implementation',
          requiredSkills: '• 4+ years of web development experience\n• Proficiency in React or Vue.js\n• Strong HTML5, CSS3, and JavaScript skills\n• Experience with responsive and adaptive design',
          preferredSkills: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Figma'],
          benefits: ['Health Insurance', 'Dental & Vision', 'Commuter Benefits', 'Learning Stipend'],
          education: 'Bachelor\'s Degree or equivalent experience',
          openings: '1',
          applyVia: 'platform',
          resumeRequirement: 'required',
          coverLetterRequirement: 'required',
          experienceLevel: 'Senior',
          languages: ['English', 'Spanish'],
          certifications: [],
          screeningQuestions: [
            {'text': 'Can you share a link to your portfolio?', 'is_required': true},
          ],
        ),
        Job(
          id: 3,
          title: 'Mobile Application Developer',
          description: '[{"insert":"Seeking a Mobile Application Developer with Flutter experience to build and maintain both iOS and Android applications. You will be an integral part of our core product team, ensuring that our mobile applications are robust, performant, and user-friendly.\\n"}]',
          category: 'Engineering',
          employmentType: 'Contract',
          workplaceType: 'Remote',
          location: 'London, UK',
          salaryMin: '£60,000',
          salaryMax: '£85,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 10)),
          closesAt: DateTime.now().add(const Duration(days: 20)),
          applicantCount: 3,
          viewCount: 210,
          responsibilities: '• Design and build advanced applications for the iOS and Android platforms\n• Collaborate with cross-functional teams to define, design, and ship new features\n• Work on bug fixing and improving application performance\n• Continuously discover, evaluate, and implement new technologies',
          requiredSkills: '• 2+ years of mobile development experience\n• Experience with Flutter and Dart\n• Understanding of Apple\'s design principles and interface guidelines\n• Familiarity with cloud message APIs and push notifications',
          preferredSkills: ['Swift', 'Kotlin', 'Firebase', 'SQLite'],
          benefits: ['Flexible Hours', 'Equipment Allowance', 'Remote Work Options'],
          education: 'Diploma or Degree in related field',
          openings: '2',
          applyVia: 'platform',
          resumeRequirement: 'required',
          coverLetterRequirement: 'optional',
          experienceLevel: 'Junior-Mid',
          languages: ['English'],
        ),
        Job(
          id: 4,
          title: 'SEO Expert',
          description: '[{"insert":"We need an SEO Expert to boost our organic reach and drive massive traffic to our main platforms. You will be conducting keyword research, competitive analysis, and executing full-scale SEO strategies.\\n"}]',
          category: 'Marketing',
          employmentType: 'Full-Time',
          workplaceType: 'Remote',
          location: 'Remote',
          salaryMin: '\$70,000',
          salaryMax: '\$100,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
          closesAt: DateTime.now().add(const Duration(days: 30)),
          applicantCount: 1,
          viewCount: 45,
          responsibilities: '• Conduct keyword research using various tools (like Ahrefs, SEMrush)\n• Optimize website content, landing pages, and paid search copy\n• Direct off-page optimization projects (e.g. link-building)\n• Monitor and evaluate search results and search performance across major search channels',
          requiredSkills: '• Proven experience as an SEO Expert or similar role\n• Familiarity with standard and current SEO practices\n• Knowledge of HTML/CSS\n• Experience with SEO reporting',
          preferredSkills: ['Google Analytics', 'Content Marketing', 'Copywriting'],
          benefits: ['Health Insurance', 'Remote Work', 'Performance Bonuses'],
          experienceLevel: 'Mid-Level',
          languages: ['English'],
          screeningQuestions: [
            {'text': 'What is your most successful SEO campaign to date?', 'is_required': true},
          ],
        ),
        Job(
          id: 5,
          title: 'Data Analyst',
          description: '[{"insert":"Join our data team as a Data Analyst. You will be responsible for interpreting data, analyzing results, and providing ongoing reports. You will work closely with management to prioritize business and information needs.\\n"}]',
          category: 'Data Science',
          employmentType: 'Full-Time',
          workplaceType: 'Onsite',
          location: 'Berlin, Germany',
          salaryMin: '€65,000',
          salaryMax: '€90,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
          closesAt: DateTime.now().add(const Duration(days: 25)),
          applicantCount: 4,
          viewCount: 150,
          responsibilities: '• Interpret data, analyze results using statistical techniques\n• Develop and implement databases, data collection systems\n• Acquire data from primary or secondary data sources\n• Identify, analyze, and interpret trends or patterns in complex data sets',
          requiredSkills: '• Proven working experience as a Data Analyst\n• Technical expertise regarding data models, database design development\n• Strong knowledge of and experience with reporting packages\n• Knowledge of statistics and experience using statistical packages for analyzing datasets',
          preferredSkills: ['Python', 'R', 'Tableau', 'PowerBI'],
          benefits: ['Relocation Assistance', 'Health Insurance', 'Gym Membership', 'Catered Lunches'],
          education: 'Master\'s Degree preferred',
          openings: '1',
          experienceLevel: 'Senior',
          languages: ['English', 'German'],
        ),
        Job(
          id: 6,
          title: 'Cybersecurity Expert',
          description: '[{"insert":"Protect our infrastructure as a Cybersecurity Expert. You will be analyzing security logs, identifying vulnerabilities, and implementing robust security measures across all our cloud environments.\\n"}]',
          category: 'Security',
          employmentType: 'Full-Time',
          workplaceType: 'Hybrid',
          location: 'Toronto, Canada',
          salaryMin: 'CAD 110,000',
          salaryMax: 'CAD 150,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 7)),
          closesAt: DateTime.now().add(const Duration(days: 14)),
          applicantCount: 2,
          viewCount: 90,
          responsibilities: '• Monitor computer networks for security issues\n• Investigate security breaches and other cybersecurity incidents\n• Install security measures and operate software to protect systems\n• Document security breaches and assess the damage they cause\n• Work with the IT team to perform tests and uncover network vulnerabilities',
          requiredSkills: '• 5+ years of experience in cybersecurity\n• Proficiency with firewalls, endpoint security, and intrusion detection systems\n• Knowledge of latest cybersecurity trends and hacker tactics\n• Strong analytical and problem-solving skills',
          preferredSkills: ['Ethical Hacking', 'Cloud Security (AWS/Azure)', 'Cryptography'],
          benefits: ['Health Insurance', 'Retirement Plan', 'Continuing Education Stipend'],
          education: 'Bachelor\'s Degree in Cybersecurity or Information Technology',
          certifications: ['CISSP', 'CEH'],
          experienceLevel: 'Senior',
        ),
        Job(
          id: 7,
          title: 'Digital Marketer',
          description: '[{"insert":"Looking for a versatile Digital Marketer to oversee our online marketing strategy. You will be managing social media campaigns, email marketing, and paid advertising.\\n"}]',
          category: 'Marketing',
          employmentType: 'Part-Time',
          workplaceType: 'Remote',
          location: 'Remote',
          salaryMin: '\$40,000',
          salaryMax: '\$60,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 4)),
          closesAt: DateTime.now().add(const Duration(days: 10)),
          applicantCount: 5,
          viewCount: 300,
          responsibilities: '• Design and oversee all aspects of our digital marketing department\n• Develop and monitor campaign budgets\n• Plan and manage our social media platforms\n• Prepare accurate reports on our marketing campaign\'s overall performance',
          requiredSkills: '• Proven experience in digital marketing\n• Demonstrable experience leading and managing SEO/SEM, marketing database, email, social media\n• Highly creative with experience in identifying target audiences',
          preferredSkills: ['HubSpot', 'Mailchimp', 'Adobe Creative Suite'],
          benefits: ['Flexible Schedule', 'Remote Work', 'Performance Bonuses'],
          experienceLevel: 'Mid-Level',
          languages: ['English'],
        ),
      ]"""

# Now replace the jobs list in the file
start_idx = content.find('super([')
end_idx = content.find(']);', start_idx)

if start_idx != -1 and end_idx != -1:
    new_content = content[:start_idx] + 'super(' + jobs_data + ');' + content[end_idx+3:]
    with open('lib/features/employer/jobs/employer_job_provider.dart', 'w') as f:
        f.write(new_content)
    print("Replaced successfully")
else:
    print("Could not find the target block")

