import re

file_path = 'lib/features/employer/jobs/employer_job_provider.dart'

with open(file_path, 'r') as f:
    content = f.read()

jobs_list = """Job(
          id: 1,
          company: Company(id: 1, name: 'TechCorp Solutions', location: 'San Francisco, CA'),
          title: 'Software Engineer',
          description: 'Full stack development role',
          category: 'Engineering',
          employmentType: 'Full-Time',
          workplaceType: 'Remote',
          location: 'San Francisco, USA',
          salaryMin: '\\$120,000',
          salaryMax: '\\$160,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(hours: 5)),
          closesAt: DateTime.now().add(const Duration(days: 28)),
          applicantCount: 524,
          viewCount: 1205,
          experienceLevel: 'Mid-Level',
        ),
        Job(
          id: 2,
          company: Company(id: 2, name: 'Global Innovations', location: 'New York, NY'),
          title: 'Product Manager',
          description: 'Lead cross-functional teams',
          category: 'Product Management',
          employmentType: 'Part-Time',
          workplaceType: 'Hybrid',
          location: 'New York, USA',
          salaryMin: '\\$90,000',
          salaryMax: '\\$130,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
          closesAt: DateTime.now().add(const Duration(days: 15)),
          applicantCount: 842,
          viewCount: 3021,
          experienceLevel: 'Senior',
        ),
        Job(
          id: 3,
          company: Company(id: 3, name: 'Design Co', location: 'London, UK'),
          title: 'UX/UI Designer',
          description: 'Create beautiful user experiences',
          category: 'Design',
          employmentType: 'Contract',
          workplaceType: 'On-site',
          location: 'London, UK',
          salaryMin: '\\$80,000',
          salaryMax: '\\$110,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 6)),
          closesAt: DateTime.now().add(const Duration(days: 20)),
          applicantCount: 312,
          viewCount: 890,
          experienceLevel: 'Mid-Level',
        ),
        Job(
          id: 4,
          company: Company(id: 4, name: 'Startup Inc', location: 'Austin, TX'),
          title: 'Marketing Intern',
          description: 'Assist with digital marketing',
          category: 'Marketing',
          employmentType: 'Internship',
          workplaceType: 'Remote',
          location: 'Austin, TX',
          salaryMin: '\\$30,000',
          salaryMax: '\\$45,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 12)),
          closesAt: DateTime.now().add(const Duration(days: 30)),
          applicantCount: 150,
          viewCount: 450,
          experienceLevel: 'Entry Level',
        ),
        Job(
          id: 5,
          company: Company(id: 5, name: 'Data Insights', location: 'Chicago, IL'),
          title: 'Temporary Data Analyst',
          description: 'Analyze data for a short-term project',
          category: 'Data Science',
          employmentType: 'Temporary',
          workplaceType: 'Hybrid',
          location: 'Chicago, IL',
          salaryMin: '\\$60,000',
          salaryMax: '\\$80,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 20)),
          closesAt: DateTime.now().add(const Duration(days: 25)),
          applicantCount: 900,
          viewCount: 4000,
          experienceLevel: 'Junior',
        ),
        Job(
          id: 6,
          company: Company(id: 1, name: 'TechCorp Solutions', location: 'San Francisco, CA'),
          title: 'Backend Engineer',
          description: 'Node.js and MongoDB',
          category: 'Engineering',
          employmentType: 'Full-Time',
          workplaceType: 'On-site',
          location: 'San Francisco, CA',
          salaryMin: '\\$140,000',
          salaryMax: '\\$180,000',
          status: JobStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 28)),
          closesAt: DateTime.now().add(const Duration(days: 10)),
          applicantCount: 210,
          viewCount: 650,
          experienceLevel: 'Senior',
        ),"""

new_content = re.sub(
    r"DemoEmployerJobsNotifier\(\)\s*: super\(\[.*?\]\);", 
    f"DemoEmployerJobsNotifier() : super([{jobs_list}]);", 
    content, 
    flags=re.DOTALL
)

with open(file_path, 'w') as f:
    f.write(new_content)

print("Updated DemoEmployerJobsNotifier!")
