import os

file_path = 'lib/features/employer/jobs/employer_job_provider.dart'

content = """import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/models/job.dart';
import '../../../core/models/company_profile.dart';

final demoEmployerJobsProvider = StateProvider<List<Job>>((ref) {
  final now = DateTime.now();
  
  final apple = CompanyProfile(
    id: 'c1',
    name: 'Apple',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg',
    industry: 'Technology',
    employeeCount: '10,000+',
    website: 'apple.com',
  );
  
  final google = CompanyProfile(
    id: 'c2',
    name: 'Google',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg',
    industry: 'Technology',
    employeeCount: '10,000+',
    website: 'google.com',
  );
  
  final meta = CompanyProfile(
    id: 'c3',
    name: 'Meta',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Meta_Platforms_Inc._logo.svg',
    industry: 'Technology',
    employeeCount: '10,000+',
    website: 'meta.com',
  );

  return [
    Job(
      id: 1,
      title: 'Senior Flutter Developer',
      description: 'Join our mobile team to build next-generation applications.',
      location: 'San Francisco, CA',
      employmentType: 'full_time',
      workplaceType: 'onsite',
      status: JobStatus.active,
      category: 'Software Engineering',
      salaryMin: r'$120k',
      salaryMax: r'$160k',
      createdAt: now.subtract(const Duration(hours: 5)),
      closesAt: now.add(const Duration(days: 28)),
      applicantCount: 524,
      viewCount: 1205,
      company: apple,
    ),
    Job(
      id: 2,
      title: 'Product Manager',
      description: 'Lead cross-functional teams to deliver great products.',
      location: 'Remote',
      employmentType: 'full_time',
      workplaceType: 'remote',
      status: JobStatus.active,
      category: 'Product Management',
      salaryMin: r'$130k',
      salaryMax: r'$180k',
      createdAt: now.subtract(const Duration(days: 2)),
      closesAt: now.add(const Duration(days: 15)),
      applicantCount: 842,
      viewCount: 3021,
      company: google,
    ),
    Job(
      id: 3,
      title: 'UX/UI Designer',
      description: 'Create beautiful and intuitive user experiences.',
      location: 'New York, NY',
      employmentType: 'part_time',
      workplaceType: 'hybrid',
      status: JobStatus.active,
      category: 'Design',
      salaryMin: r'$80k',
      salaryMax: r'$110k',
      createdAt: now.subtract(const Duration(days: 6)),
      closesAt: now.add(const Duration(days: 20)),
      applicantCount: 312,
      viewCount: 890,
      company: meta,
    ),
    Job(
      id: 4,
      title: 'Backend Engineer',
      description: 'Design and implement scalable backend services.',
      location: 'London, UK',
      employmentType: 'contract',
      workplaceType: 'remote',
      status: JobStatus.active,
      category: 'Software Engineering',
      salaryMin: r'$100k',
      salaryMax: r'$140k',
      createdAt: now.subtract(const Duration(days: 12)),
      closesAt: now.add(const Duration(days: 30)),
      applicantCount: 150,
      viewCount: 450,
      company: google,
    ),
    Job(
      id: 5,
      title: 'Marketing Intern',
      description: 'Learn and assist in marketing campaigns.',
      location: 'Chicago, IL',
      employmentType: 'internship',
      workplaceType: 'onsite',
      status: JobStatus.active,
      category: 'Marketing',
      salaryMin: r'$30k',
      salaryMax: r'$45k',
      createdAt: now.subtract(const Duration(days: 20)),
      closesAt: now.add(const Duration(days: 25)),
      applicantCount: 900,
      viewCount: 4000,
      company: apple,
    ),
    Job(
      id: 6,
      title: 'Temporary Data Analyst',
      description: 'Analyze data for a short-term project.',
      location: 'Seattle, WA',
      employmentType: 'temporary',
      workplaceType: 'hybrid',
      status: JobStatus.active,
      category: 'Data Science',
      salaryMin: r'$60k',
      salaryMax: r'$80k',
      createdAt: now.subtract(const Duration(days: 28)),
      closesAt: now.add(const Duration(days: 10)),
      applicantCount: 210,
      viewCount: 650,
      company: meta,
    ),
    Job(
      id: 7,
      title: 'iOS Engineer',
      description: 'Build native iOS applications.',
      location: 'Cupertino, CA',
      employmentType: 'full_time',
      workplaceType: 'onsite',
      status: JobStatus.active,
      category: 'Software Engineering',
      salaryMin: r'$140k',
      salaryMax: r'$190k',
      createdAt: now.subtract(const Duration(days: 1)),
      closesAt: now.add(const Duration(days: 30)),
      applicantCount: 650,
      viewCount: 2100,
      company: apple,
    ),
    Job(
      id: 8,
      title: 'Android Developer',
      description: 'Create Android apps using Kotlin.',
      location: 'Mountain View, CA',
      employmentType: 'contract',
      workplaceType: 'remote',
      status: JobStatus.active,
      category: 'Software Engineering',
      salaryMin: r'$110k',
      salaryMax: r'$150k',
      createdAt: now.subtract(const Duration(days: 4)),
      closesAt: now.add(const Duration(days: 20)),
      applicantCount: 420,
      viewCount: 1500,
      company: google,
    ),
    Job(
      id: 9,
      title: 'Data Scientist',
      description: 'Machine learning and AI research.',
      location: 'Menlo Park, CA',
      employmentType: 'full_time',
      workplaceType: 'hybrid',
      status: JobStatus.active,
      category: 'Data Science',
      salaryMin: r'$160k',
      salaryMax: r'$220k',
      createdAt: now.subtract(const Duration(days: 8)),
      closesAt: now.add(const Duration(days: 40)),
      applicantCount: 780,
      viewCount: 2800,
      company: meta,
    ),
    Job(
      id: 10,
      title: 'Frontend Developer',
      description: 'Build responsive web apps with React.',
      location: 'Austin, TX',
      employmentType: 'part_time',
      workplaceType: 'remote',
      status: JobStatus.active,
      category: 'Software Engineering',
      salaryMin: r'$70k',
      salaryMax: r'$90k',
      createdAt: now.subtract(const Duration(days: 15)),
      closesAt: now.add(const Duration(days: 25)),
      applicantCount: 560,
      viewCount: 1900,
      company: google,
    ),
  ];
});
"""

with open(file_path, 'w') as f:
    f.write(content)

print("Created comprehensive demo jobs!")
